import re

with open("src/lib/academy-data.ts", "r") as f:
    content = f.read()

translations = {
    "Tìm hiểu Veasyble là gì và campaign execution hoạt động như thế nào": "Learn what Veasyble is and how campaign execution works",
    "Veasyble kết nối Brand với Executor để thực thi campaign tại điểm bán": "Veasyble connects Brands with Executors to execute campaigns at POS",
    "Mỗi task bao gồm: nhận materials, di chuyển đến store, setup, và submit PoP": "Each task includes: pick up materials, go to store, setup, and submit PoP",
    "Executor được trả theo task hoàn thành": "Executors are paid per completed task",
    "Veasyble platform tự động assign task dựa trên availability và rating": "Veasyble platform automatically assigns tasks based on availability and rating",
    "Veasyble hoạt động trong lĩnh vực nào?": "What industry does Veasyble operate in?",
    "Thiết kế campaign": "Campaign design",
    "Giao hàng": "Delivery",
    "Setup campaign tại store": "Setup campaign at store",
    "Quản lý brand": "Brand management",
    "Ai assign task cho Executor?": "Who assigns tasks to Executors?",
    "Executor tự chọn": "Executors choose themselves",
    "Sau khi hoàn thành task, Executor cần làm gì?": "What should an Executor do after completing a task?",
    "Gọi điện báo": "Call to report",
    "Gửi email": "Send email",
    "Submit PoP qua app": "Submit PoP via app",
    "Không cần làm gì": "Do nothing",
    "GPS check-in, selfie với bảng hiệu, và quy trình làm việc tại store": "GPS check-in, selfie with store sign, and store workflow",
    "GPS check-in xác nhận bạn có mặt tại đúng địa điểm và đúng thời gian": "GPS check-in confirms you are at the correct location and time",
    "Selfie cần có bảng hiệu store rõ ràng phía sau": "Selfie must clearly show the store sign in the background",
    "SOP checklist hướng dẫn từng bước setup campaign": "SOP checklist guides the step-by-step campaign setup",
    "Nếu gặp vấn đề tại store, raise dispute trong app - không tự ý xử lý": "If you encounter an issue at the store, raise a dispute in the app - do not handle it yourself",
    "GPS check-in xác nhận điều gì?": "What does GPS check-in confirm?",
    "Executor đã in materials": "Executor has printed materials",
    "Executor có mặt tại đúng địa điểm": "Executor is at the correct location",
    "Task đã hoàn thành": "Task is completed",
    "Materials đã được nhận": "Materials have been received",
    "Selfie cần có gì trong ảnh?": "What must be in the selfie?",
    "Chỉ khuôn mặt": "Only the face",
    "Bảng hiệu store rõ ràng": "Clear store sign",
    "Hóa đơn": "Receipt",
    "Nếu trễ hơn 15 phút so với giờ check-in?": "If you are more than 15 minutes late to check-in?",
    "Không sao": "It's fine",
    "Bị trừ một phần pay": "Pay is partially deducted",
    "Task bị hủy và surge ngay": "Task is cancelled and surged immediately",
    "Bị suspend": "Account suspended",
    "SOP checklist dùng để làm gì?": "What is the SOP checklist used for?",
    "Xác nhận danh tính": "Identity verification",
    "Hướng dẫn từng bước setup campaign": "Step-by-step campaign setup guide",
    "Tính lương": "Calculate pay",
    "Liên hệ brand": "Contact brand",
    "Khi store từ chối cho vào, Executor nên?": "When the store refuses entry, the Executor should?",
    "Bỏ về": "Leave",
    "Tự xử lý": "Handle it themselves",
    "Raise dispute trong app - không bị trừ pay": "Raise dispute in app - no pay deduction",
    "Gọi cho brand": "Call the brand",
    "Cách chụp ảnh đúng chuẩn và submit PoP thành công": "How to take correct photos and successfully submit PoP",
    "PoP cần bao gồm ảnh + metadata + timestamp": "PoP must include photo + metadata + timestamp",
    "Timestamp xác nhận ảnh được chụp đúng lúc check-in": "Timestamp confirms the photo was taken during check-in",
    "Nếu ảnh PoP bị reject do mờ, chụp lại tại chỗ ngay": "If PoP photo is rejected due to blur, retake immediately",
    "Sau khi submit, task chuyển sang trạng thái Under Review": "After submission, the task moves to Under Review status",
    "PoP cần bao gồm gì?": "What must PoP include?",
    "Chỉ ảnh setup": "Only setup photo",
    "Ảnh + metadata + timestamp": "Photo + metadata + timestamp",
    "Video quay toàn bộ": "Full video recording",
    "Chữ ký retailer": "Retailer signature",
    "Tại sao timestamp quan trọng?": "Why is the timestamp important?",
    "Để tính lương": "To calculate pay",
    "Xác nhận ảnh chụp đúng lúc check-in": "Confirms photo was taken during check-in",
    "Để liên hệ brand": "To contact brand",
    "Không quan trọng": "Not important",
    "Nếu ảnh PoP bị reject do mờ?": "If PoP photo is rejected due to blur?",
    "Báo Veasyble Team": "Report to Veasyble Team",
    "Chụp lại tại chỗ ngay": "Retake immediately on site",
    "Gửi email": "Send email",
    "Bỏ qua": "Ignore",
    "Metadata ảnh dùng để?": "What is photo metadata used for?",
    "Trang trí": "Decoration",
    "Detect chỉnh sửa hoặc giả mạo": "Detect editing or forgery",
    "Lưu tên executor": "Save executor name",
    "Tính tiền": "Calculate money",
    "Sau khi submit PoP thành công?": "After successful PoP submission?",
    "Nhận tiền ngay": "Receive money immediately",
    "Task chuyển sang Under Review": "Task moves to Under Review",
    "Executor tự đánh giá": "Executor self-evaluates",
    "Brand liên hệ": "Brand contacts",
    "Chính sách trễ giờ, huỷ task, và hệ thống rating của Veasyble": "Lateness policy, task cancellation, and Veasyble rating system",
    "Rating được tính từ trung bình của Brand + Retailer đã rate bạn": "Rating is calculated from the average of Brand + Retailer ratings",
    "Rating >= 4.0 được coi là Healthy": "Rating >= 4.0 is considered Healthy",
    "Dưới 3.5 sẽ nhận auto-reminder và Veasyble review": "Below 3.5 triggers an auto-reminder and Veasyble review",
    "Huỷ task sau khi đã in materials sẽ bị trừ rating nặng và flag tài khoản": "Cancelling a task after printing materials incurs a heavy rating penalty and account flag",
    "Nếu trễ check-in 10 phút, bạn sẽ bị xử lý như thế nào?": "What happens if you check-in 10 minutes late?",
    "Không sao cả": "Nothing happens",
    "Trừ một phần thu nhập tương ứng": "Deduct proportional pay",
    "Task bị huỷ ngay lập tức": "Task cancelled immediately",
    "Bị khóa tài khoản": "Account locked",
    "Nếu trễ check-in 20 phút?": "If you check-in 20 minutes late?",
    "Vẫn được làm bình thường": "Can still work normally",
    "Trừ 50% lương": "50% pay deduction",
    "Task tự động bị huỷ, nhường cho executor khác (surge)": "Task automatically cancelled and given to another executor (surge)",
    "Chỉ bị nhắc nhở": "Only a warning",
    "Rating của Executor được tính dựa trên?": "Executor rating is based on?",
    "Điểm do Veasyble quyết định mãi mãi": "Score decided by Veasyble forever",
    "Chỉ Brand đánh giá": "Only Brand review",
    "Điểm đánh giá từ Brand và Retailer (sau job đầu tiên)": "Rating from Brand and Retailer (after first job)",
    "Executor tự chấm điểm": "Executor self-rates",
    "Mức rating nào được coi là Healthy?": "What rating is considered Healthy?",
    "3.0 trở lên": "3.0 or above",
    "3.5 trở lên": "3.5 or above",
    "4.0 trở lên": "4.0 or above",
    "5.0 tuyệt đối": "Perfect 5.0",
    "Khi đến cửa hàng nhưng bị từ chối cho vào setup, bạn nên?": "When arriving at the store but refused entry for setup, you should?",
    "Tự đi về và chịu mất task": "Leave and lose the task",
    "Chọn 'Cửa hàng từ chối' trong app, giữ nguyên thu nhập": "Select 'Store refused entry' in app, keep full pay",
    "Cãi nhau với bảo vệ": "Argue with security",
    "Gọi ngay cho Brand để phàn nàn": "Call Brand immediately to complain",
    "Executor có nhiệm vụ gì?": "What is the Executor's task?",
}

for vi, en in translations.items():
    content = content.replace(vi, en)

with open("src/lib/academy-data.ts", "w") as f:
    f.write(content)
